# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: verrazzano.io/v1beta1
kind: VerrazzanoModel
metadata:
  name: sock-shop-model
  namespace: default
spec:
  description: "Sock Shop Model"
  coherenceClusters:
    - name: "carts"
      image: "ghcr.io/helidon-sockshop/carts-coherence:2.2.0
      imagePullSecrets:
        - name: github-packages
        - name: ocr
      connections:
        - ingress:
            - name: "carts-ingress"
              match:
                - uri:
                    prefix: /carts
      ports:
        - name: http
          port: 7001
          service:
            name: carts
            port: 80
    - name: "catalogue"
      image: "ghcr.io/helidon-sockshop/catalog-coherence:2.2.0"
      imagePullSecrets:
        - name: github-packages
        - name: ocr
      connections:
        - ingress:
            - name: "catalogue-ingress"
              match:
                - uri:
                    prefix: /catalogue
      ports:
        - name: http
          port: 7001
          service:
            name: catalogue
            port: 80
    - name: "orders"
      image: "ghcr.io/helidon-sockshop/orders-coherence:2.2.0"
      imagePullSecrets:
        - name: github-packages
        - name: ocr
      connections:
        - ingress:
            - name: "orders-ingress"
              match:
                - uri:
                    prefix: /orders
      ports:
        - name: http
          port: 7001
          service:
            name: orders
            port: 80
    - name: "payment"
      image: "ghcr.io/helidon-sockshop/payment-coherence:2.2.0"
      imagePullSecrets:
        - name: github-packages
        - name: ocr
      connections:
        - ingress:
            - name: "payment-ingress"
              match:
                - uri:
                    prefix: /payment
      ports:
        - name: http
          port: 7001
          service:
            name: payment-http
            port: 80
    - name: "shipping"
      image: "ghcr.io/helidon-sockshop/shipping-coherence:2.2.0"
      imagePullSecrets:
        - name: github-packages
        - name: ocr
      connections:
        - ingress:
            - name: "shipping-ingress"
              match:
                - uri:
                    prefix: /shipping
      ports:
        - name: http
          port: 7001
          service:
            name: shipping-http
            port: 80
    - name: "user"
      image: "ghcr.io/helidon-sockshop/users-coherence:2.2.0"
      imagePullSecrets:
        - name: github-packages
        - name: ocr
      connections:
        - ingress:
            - name: "user-ingress"
              match:
                - uri:
                    prefix: /register
                - uri:
                    prefix: /login
                - uri:
                    prefix: /addresses
                - uri:
                    prefix: /customers
                - uri:
                    prefix: /cards
      ports:
        - name: http
          port: 7001
          service:
            name: user
            port: 80
