# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: springboot-component
  namespace: oam-springboot
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    metadata:
      name: springboot-workload
      namespace: oam-springboot
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: "phx.ocir.io/stevengreenberginc/testimage/spring-boot-verrazzano:0.0.3"
        ports:
          - containerPort: 8080
            name: springboot
