# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

global:
  hub: istio
  tag: 1.4.10
gateways:
  istio-ingressgateway:
    ports:
    - port: 80
      targetPort: 80
      name: http2
      nodePort: 31380
    - port: 443
      name: https
      nodePort: 31390
sidecarInjectorWebhook:
  rewriteAppHTTPProbe: true
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: 6.4.4
prometheus:
  hub: bitnami
  tag: 2.13.1
istiocoredns:
  coreDNSImage: coredns/coredns
  coreDNSTag: 1.8.0
  coreDNSPluginImage: istio/coredns-plugin:0.2-istio-1.1
